version: "2.2"
services:
  elasticsearch:
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s localhost:9200/_cat/health | grep docker-cluster",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    ports: 
      - 9200:9200
    build:
      context: ./dockerfiles/elasticsearch
      dockerfile: Dockerfile
  pythonscript:
    depends_on:
      elasticsearch:
        condition: service_healthy
    build:
      context: ./dockerfiles/pythonscript
      dockerfile: Dockerfile
  kibana:
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports: 
      - 5601:5601
    build:
      context: ./dockerfiles/kibana
      dockerfile: Dockerfile