FROM elasticsearch:8.3.1
ENV node.name es01
ENV xpack.security.enabled false
ENV xpack.security.http.ssl.enabled false  
ENV xpack.security.transport.ssl.enabled false
ENV cluster.initial_master_nodes es01
ENV KIBANA_PASSWORD kibana
ENV ELASTIC_PASSWORD elastic